ADD_ROLL = "ADD"
USE_SEED = "USE"
BACK = "BACK"

FLUSH_ROLLS = 0

DICE_ROLLED_1 = 1
DICE_ROLLED_2 = 2
DICE_ROLLED_3 = 3
DICE_ROLLED_4 = 4
DICE_ROLLED_5 = 5
DICE_ROLLED_6 = 6

PIPS = [DICE_ROLLED_1,
        DICE_ROLLED_2,
        DICE_ROLLED_3,
        DICE_ROLLED_4,
        DICE_ROLLED_5,
        DICE_ROLLED_6,]
